### ISSUE TITLE
Issue su iscrizione ai corsi

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/contributo2_PHP-MySQL_Zanchetta-Aquilina#1]
Per: @Orioncode0 
L'iscrizione ai corsi funziona correttamente. Sarebbe carino aggiungere una sorta di messaggio di avvenuta iscrizione; posso pensarci io, se sei d'accordo. C'è un piccolo bug: compare un errore nella pagina web ad iscrizione avvenuta (viene ignorata la nuova "session_start()"); sarebbe da fixare, perché lo stile della pagina si rovina... manca inoltre qualche collegamento con i button che avevamo deciso di aggiungere; ci lavoro su qualche minuto.

Update: potrebbe essere necessaria una funzionalità di cancellazione dell'iscrizione (come in classroom) dal singolo corso. Che ne pensi?

Altra cosa: dovremmo aggiungere le descrizioni relative ai corsi e alle informazioni sui professori nello script di creazione della base di dati. Lo facciamo all'ultimo, oppure un po' alla volta?

**Comment by Mattia-Aquilina** [comment]
Per: @luca-zanchetta 
Non mi ero accorto di questi bug durante lo sviluppo della funzionalità di iscrizione però ho visto che hai già provveduto a risolverli. Non mi resta che dedicarmi all'aggiunta delle informazioni relative ai corsi e alla costruzione della pagina per visualizzarle.

**Comment by luca-zanchetta** [comment]
Per: @Orioncode0 
Ottimo. Ho dato un'occhiata ai commit; domani farò altri test e ti faccio sapere se funziona tutto
