### ISSUE TITLE
Script di creazione db

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/contributo2_PHP-MySQL_Zanchetta-Aquilina#2]
Per: @Orioncode0 
Sarebbe il caso di implementare, prima di fare qualsiasi prova sul server lweb, il famoso "merge" dei due script di installazione e di update del db, in modo da non dover per forza eseguire ogni volta due script per avere la piena funzionalità del sito. 
Bisogna anche completare il file README.md; farò una prima versione io, poi ci confrontiamo sul contenuto

**Comment by Mattia-Aquilina** [comment]
Per: @luca-zanchetta 
Mi dedico allora al merge dei 2 script php. Non appena eseguito il commit procederò a chiudere l'issue.
