### ISSUE TITLE
Problema scroll multipli

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/contributo2_PHP-MySQL_Zanchetta-Aquilina#3]
Per: @Orioncode0 
Come da accordi privati, ho provveduto ad effettuare il merge degli script di installazione e di aggiornamento del db. Consiglio di effettuare un drop database prima di eseguire di nuovo lo script di installazione.

Altro problema: nella form di login e nella form di registrazione compaiono due (fastidiose) scrollbar; non riesco a sistemare questo problema. La situazione desiderabile sarebbe quella in cui sia il solo contenuto del div.body a scrollare (completamente! Scrolla solo in modo parziale; che fastidio). Poi, dopo un update del readme, potremmo considerare terminato il lavoro.

**Comment by Mattia-Aquilina** [comment]
Per: @luca-zanchetta 
Mi sono occupato del problema delle scrollbar e sono riuscito a risolverlo. Ho caricato la versione corretta nell'ultimo commit.
